### ISSUE TITLE
ReferenceError: Can't find variable: CordovaWebsocketPlugin

### ISSUE THREAD

**Issue by minister19** [HomeControlAS/cordova-plugin-advanced-websocket#16] opened 2019-08-31 14:03 UTC
Hello, I am using Adobe phonegap online build, trying to build for ios platform, the page shows websocket plugin installed as follows

![image](https://user-images.githubusercontent.com/12003171/64064943-505dba00-cc3a-11e9-9ddb-850465b14cf0.png)

and the build log is successful with some warnings:
![image](https://user-images.githubusercontent.com/12003171/64065047-21941380-cc3b-11e9-9c6d-eb83e1597c7b.png)
![image](https://user-images.githubusercontent.com/12003171/64065022-01fceb00-cc3b-11e9-8299-75acb75f2aca.png)

But the plugin is missing during runtime as follows:
![image](https://user-images.githubusercontent.com/12003171/64064976-9286fb80-cc3a-11e9-8cc6-9647e99a5f52.png)

Is there anything wrong with my installation? Thanks

**Comment by chax** [comment] 2019-09-11 00:48
I never used Adobe Phonegap Build so i can't tell what is wrong here. Did you try to build app locally on Mac for iOS or on Linux/Mac/Windows for Android?
Those warnings are just warnings and i would be surprised if they are the cause of your problem.
Last question is, what did you use to debug (last screenshot).

Keep in mind that this plugin works only when app is running natively on iOs or Android and you can't use it in Browser (or platform electron).

**Comment by chax** [comment] 2021-02-22 12:29
Closing this issue as it's been more than one year without any additional activity.

**Closed** 2021-02-22 12:32 UTC
